---
- name: Configure secret
  ansible.builtin.shell: >
    gh secret --repo {{ repo }} set --env {{ env.env_name }} {{ item.gh_secret_name }} --body {{ item.gh_secret_value }}
  changed_when: true
  no_log: false
  loop: "{{  env.env_secrets | dict2items('gh_secret_name', 'gh_secret_value') }}"
