---
- name: Create github environment
  ansible.builtin.shell: >
    gh api --method PUT -H "Accept: application/vnd.github+json" repos/{{ repo }}/environments/{{ env.env_name }}
  changed_when: true
  loop: "{{ env_secrets | dict2items(key_name='env_name', value_name='env_secrets') }}"
  loop_control:
    loop_var: env

- name: For each secret in environment
  ansible.builtin.include_tasks: gh-set-secret.yml
  loop: "{{ env_secrets | dict2items(key_name='env_name', value_name='env_secrets') }}"
  loop_control:
    loop_var: env
