# TODO: allow layered loading from other repos like dependabot config
# Symlink this as ~/pre.yml and use https://github.com/pycontribs/gh-pre
# This file documents repositories that are nurtured by Ansible DevTools team.
# Not all these repos are fully managed or maintained by the team.
# We aim to use this file when performing maintenance and audit.
# to review open pull requests and issues.
_version: 1
_extends: gh-org/gh-repo
repos:
  # repo key can be 'gh-org/gh-repo' or other simple, override url could be
  # configured using 'repo:' key.
  _default:
    # special meaning, all other keys will inherit attributes this entry
    group: primary
  ansible-collections/community.molecule:
    section: community
  ansible-community/molecule-plugins:
    section: community
  ansible/ansible-backstage-plugins:
    section: experimental
  ansible/ansible-compat: {}
  ansible/ansible-creator:
    section: experimental
  ansible/ansible-dev-environment:
    section: experimental
  ansible/ansible-dev-tools: {}
  ansible/ansible-lint: {}
  ansible/ansible-navigator: {}
  ansible/ansible-workspace-env-reference-image:
    section: community
  ansible/community-ansible-dev-tools-image: {}
  ansible/creator-ee:
    section: deprecated
  ansible/mkdocs-ansible:
    section: community
  ansible/molecule: {}
  ansible/pytest-ansible:
    section: experimental
  ansible/team-devtools: {}
  ansible/tox-ansible:
    section: experimental
  ansible/vscode-ansible: {}
  pycontribs/enrich:
    section: community
  pycontribs/subprocess-tee:
    section: community
sections:
  community: null
  deprecated: null
  experimental: null
  primary: null
  # unmaintained, obsoleted or archived:
  # - ansible-community/protogen # deprecated?
  # - ansible-community/role2collection
  # - ansible/ansible-language-server (now part vscode-ansible)
  # - ansible/ansible-lint-action (now part of ansible-lint)
  # - pycontribs/selinux
  # - pytest-molecule#
