---
- name: Deploy BOT_PAT secret
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Load repositories
      ansible.builtin.include_vars:
        file: ../config/devtools.yml
        name: devtools

    - name: Display info
      ansible.builtin.debug:
        msg: "{{ item }}"
      loop: "{{ env_secrets | dict2items(key_name='env_name', value_name='env_secrets') }}"

    - name: Loop over repositories
      ansible.builtin.include_tasks: tasks/gh-set-env-secrets.yml
      loop: "{{ devtools.repos }}"
      loop_control:
        label: "{{ repo }}"
        loop_var: repo
