---
# push workflow is shared and expected to perform actions after a merge happens
# on a maintenance branch (default or release). For example updating the
# draft release-notes.
name: push

on:
  push:
    # branches to consider in the event; optional, defaults to all
    branches:
      - main
      - releases/**
      - stable/**
  workflow_call: # allows reuse of this workflow from other devtools repos

jobs:
  update_release_draft:
    runs-on: ubuntu-22.04
    steps:
      - uses: release-drafter/release-drafter@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
